### Create a Grant
# @name createGrant
POST {{base}}/grants
Content-Type: application/json

{
  "code": "laying-hen-housing",
  "metadata": {
    "description": "Laying Hen Housing for Health and Welfare",
    "startDate": "2026-01-01T00:00:00Z"
  },
  "actions": [
    {
      "name": "get-prices",
      "url": "https://httpbin.org/anything",
      "method": "GET"
    },
    {
      "name": "calc-totals",
      "url": "https://httpbin.org/post",
      "method": "POST"
    }
  ],
  "questions": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "surname": {
        "type": "string"
      },
      "age": {
        "type": "integer",
        "minimum": 0
      },
      "isAgent": {
        "type": "boolean"
      },
      "address": {
        "type": "object",
        "properties": {
          "street": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "postCode": {
            "type": "string"
          }
        },
        "required": [
          "street",
          "city",
          "postCode"
        ]
      }
    },
    "required": [
      "name",
      "surname",
      "age",
      "isAgent"
    ],
    "dependentRequired": {
      "isAgent": [
        "address"
      ]
    }
  }
}

### Get a Grant
# @name getGrant
GET {{base}}/grants/{{createGrant.response.body.code}}

### Get all Grants
# @name getGrants
GET {{base}}/grants

### Invoke external GET action
# @name invokeGetAction
GET {{base}}/grants/{{createGrant.response.body.code}}/actions/get-prices/invoke
Content-Type: application/json

### Invoke external POST action
# @name invokePostAction
POST {{base}}/grants/{{createGrant.response.body.code}}/actions/calc-totals/invoke
Content-Type: application/json

{
  "test": 1
}
