### Create a Grant

# @name createGrant

POST {{base}}/grants HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{serviceToken}}

< ./test/fixtures/pmf-grant-definition.json


### Get a Grant

# @name getGrant

GET {{base}}/grants/pigs-might-fly HTTP/1.1
Authorization: Bearer {{serviceToken}}


### Get all Grants

# @name getGrants

GET {{base}}/grants HTTP/1.1
Authorization: Bearer {{serviceToken}}


### Invoke external POST action

# @name invokePostAction

POST {{base}}/grants/pigs-might-fly/actions/calculate-pig-totals/invoke HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{serviceToken}}

{
  "test": 1
}


### Submit application

# @name submitApplication

POST {{base}}/grants/pigs-might-fly/applications HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{serviceToken}}

{
  "answers": {
    "berkshirePigsCount": 3,
    "britishLandracePigsCount": 2,
    "isPigFarmer": true,
    "otherPigsCount": 3,
    "totalPigs": 10,
    "whitePigsCount": 2
  },
  "metadata": {
    "clientRef": "{{$uuid}}",
    "crn": "1234567890",
    "defraId": "1234567890",
    "frn": "1234567890",
    "sbi": "1234567890",
    "submittedAt": "{{$date}}T12:00:00Z"
  }
}


### Get health

# @name getHealth

GET {{base}}/health HTTP/1.1
