x-mongo-common: &mongo-common
  image: mongo:6.0.13
  networks: [cdp-tenant]
  healthcheck:
    test:
      [
        "CMD-SHELL",
        "mongosh --quiet --eval 'db.runCommand({ping:1}).ok' || exit 1",
      ]
    interval: 10s
    timeout: 5s
    retries: 10

services:
  localstack:
    image: localstack/localstack:4.3.0
    ports:
      - "${LOCALSTACK_PORT:-4566}:4566"
    env_file:
      - "compose/aws.env"
    environment:
      DEBUG: 1
      LS_LOG: DEBUG
      SERVICES: sqs,sns
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    networks:
      - cdp-tenant

  mongodb:
    <<: *mongo-common
    container_name: mongodb
    ports: ["${MONGO_PORT_1:-27017}:27017"]
    command:
      ["mongod", "--replSet", "mongoRepl", "--bind_ip", "localhost,mongodb"]
    volumes: ["mongodb-data-1:/data/db"]
    restart: always

  mongodb-2:
    <<: *mongo-common
    container_name: mongodb-2
    ports: ["${MONGO_PORT_2:-27018}:27017"]
    command:
      ["mongod", "--replSet", "mongoRepl", "--bind_ip", "localhost,mongodb-2"]
    volumes: ["mongodb-data-2:/data/db"]
    restart: always

  mongodb-3:
    <<: *mongo-common
    container_name: mongodb-3
    ports: ["${MONGO_PORT_3:-27019}:27017"]
    command:
      ["mongod", "--replSet", "mongoRepl", "--bind_ip", "localhost,mongodb-3"]
    volumes: ["mongodb-data-3:/data/db"]
    restart: always

  mongo-ready:
    container_name: "mongo-ready"
    image: mongo:6.0.13
    networks: [cdp-tenant]
    environment:
      PRIMARY: "mongodb:27017"
      REPLSET: "mongoRepl"
    volumes:
      - ./scripts/init-rs.sh:/init-rs.sh:ro
    entrypoint: ["/bin/bash", "/init-rs.sh"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh 'mongodb://mongodb:27017/?directConnection=true' --quiet --eval 'db.hello().isWritablePrimary' | grep -q true || exit 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 60

  gas:
    build: .
    ports:
      - "${GAS_PORT:-3000}:3000"
    links:
      - "localstack:localstack"
      - "mongodb:mongodb"
      - "mongo-ready:mongo-ready"
    depends_on:
      localstack:
        condition: service_healthy
      mongo-ready:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://mongodb:27017,mongodb-2:27017,mongodb-3:27017/?replicaSet=mongoRepl"
    networks:
      - cdp-tenant
    develop:
      watch:
        - path: ./src
          target: /home/node/src
          action: sync+restart
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./migrate-mongo-config.js:/home/node/migrate-mongo-config.js
      - ./migrations:/home/node/migrations
      - ./package.json:/home/node/package.json

volumes:
  mongodb-data-1:
  mongodb-data-2:
  mongodb-data-3:

networks:
  cdp-tenant:
    driver: bridge
