services:
  grants-ui:
    environment:
      GAS_API_URL: "http://gas:3000"

  gas:
    build:
      context: ../fg-gas-backend
    networks:
      - grants-ui-net
    ports:
      - "3002:3000"
    env_file:
      - ../fg-gas-backend/.env
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongodb:27017/?replicaSet=mongoRepl
      AWS_ENDPOINT_URL: "http://localstack:4566"
    depends_on:
      mongo-ready:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      localstack:
        condition: service_healthy
    volumes:
      - ../fg-gas-backend/migrate-mongo-config.js:/home/node/migrate-mongo-config.js
      - ../fg-gas-backend/migrations:/home/node/migrations
      - ../fg-gas-backend/package.json:/home/node/package.json

  localstack:
    volumes:
      - ../fg-gas-backend/compose/start-localstack.sh:/etc/localstack/init/ready.d/start-gas-localstack.sh
