services:
  mongodb:
    image: mongo:6.0.13
    command: mongod --port ${MONGO_PORT:-27017}
    networks:
      - cdp-tenant
    ports:
      - "${MONGO_PORT:-27017}:${MONGO_PORT:-27017}"
    volumes:
      - mongodb-data:/data
    restart: always

  gas:
    build: .
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    links:
      - "mongodb:mongodb"
    depends_on:
      mongodb:
        condition: service_started
    environment:
      PORT: ${PORT:-3001}
      NODE_ENV: development
      MONGO_URI: mongodb://mongodb:${MONGO_PORT:-27017}/
    networks:
      - cdp-tenant
    develop:
      watch:
        - path: ./src
          target: /home/node/src
          action: sync+restart

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
