services:
  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data
    restart: always

  gas:
    build: ./
    ports:
      - '3001:3001'
    links:
      - 'mongodb:mongodb'
    depends_on:
      mongodb:
        condition: service_started
    environment:
      PORT: 3001
      NODE_ENV: development
      MONGO_URI: mongodb://mongodb:27017/
    networks:
      - cdp-tenant

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
