services:
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - "${LOCALSTACK_PORT:-4566}:4566" # LocalStack Gateway
    env_file:
      - "compose/aws.env"
    environment:
      DEBUG: 1
      LS_LOG: DEBUG # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ["CMD", "curl", "localhost:4566"]
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb-data:/data
    restart: always

  gas:
    build: .
    ports:
      - "${GAS_PORT:-3000}:3000"
    links:
      - "mongodb:mongodb"
    depends_on:
      mongodb:
        condition: service_started
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongodb:27017/
    networks:
      - cdp-tenant
    develop:
      watch:
        - path: ./src
          target: /home/node/src
          action: sync+restart
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
