services:
  localstack:
    image: localstack/localstack:4.3.0
    ports:
      - "${LOCALSTACK_PORT:-4566}:4566"
    env_file:
      - "compose/aws.env"
    environment:
      DEBUG: 1
      LS_LOG: DEBUG
      SERVICES: sqs,sns
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb-data:/data
    restart: always

  gas:
    build: .
    ports:
      - "${GAS_PORT:-3000}:3000"
    links:
      - "localstack:localstack"
      - "mongodb:mongodb"
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongodb:27017/
    networks:
      - cdp-tenant
    # healthcheck:
    #   test: curl "http://localhost:${GAS_PORT:-3000}/health" || exit 1
    #   interval: 20s
    #   retries: 5
    #   start_period: 20s
    #   timeout: 10s
    develop:
      watch:
        - path: ./src
          target: /home/node/src
          action: sync+restart
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
