services:
  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb-data:/data
    restart: always

  gas:
    build: .
    ports:
      - "${GAS_PORT:-3000}:3000"
    links:
      - "mongodb:mongodb"
    depends_on:
      mongodb:
        condition: service_started
    environment:
      PORT: 3000
      NODE_ENV: development
      MONGO_URI: mongodb://mongodb:27017/
    networks:
      - cdp-tenant
    develop:
      watch:
        - path: ./src
          target: /home/node/src
          action: sync+restart
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
